### ISSUE TITLE
Create OnChanges Lifecycle Hooks

### ISSUE THREAD

**Issue by abalad** [tb/ng2-gravatar#10]
First of all congratulations for this very useful directive;)

In my application I receive the user's email via the GET http method, but this is a promise, but its directive only takes the email value in the OnInit event, the correct one would be to create the URL of the gravatar in the OnChanges event, so that you can get always updated emails.

**My Proposal**

```
  ngOnInit() {
    this.setUrlGravatar(this.email);
  }

  ngOnChanges(changes:any){
    this.setUrlGravatar(changes['email'].currentValue);
  }

  setUrlGravatar(email:any){
    this.elementRef.nativeElement.src = `//www.gravatar.com/avatar/${md5(email)}?s=${this.size}&d=${this.fallback}`;
  }
```

**Comment by zurfyx** [comment]
It looks good to me (and I believe it should work just fine). Do you want to submit a pull request?

Just a couple things:

1. `changes: SimpleChanges`

2. Unchanged properties won't be sent through `ngOnchanges`

```
if (changes['email']) {
  ...
}
```

**Comment by abalad** [comment]
@zurfyx That's really what I ended up doing. But I think it would be interesting to change it in the OnChanges event.

Anyway I sent a PR. Thank you so much

**Comment by tb** [comment]
@abalad Thank you for contributing, PR is merged and npm package published.
