### ISSUE TITLE
https

### ISSUE THREAD

**Issue by binarious** [tb/ng2-gravatar#2]
You should use https for gravatar.com or otherwise this directive can't be used on https sites.

**Comment by rwngallego** [comment]
I'm having problems when I load Gravatar images with this component because it is requesting the http resource and not https.

**Comment by zurfyx** [comment]
@rwngallego https://github.com/tb/ng2-gravatar/pull/13 should force `https`.

Either way, Gravatar supports both `http` and `https` endpoints. If your site is running with `https`, it should be picking the `https` one by default.
