### ISSUE TITLE
Unexpected value 'Gravatar' ... declared by the module ...

### ISSUE THREAD

**Issue by stkrwilson** [tb/ng2-gravatar#6]
error compiling when trying to build project using `ng build --prod`.

"ERROR in Unexpected value 'Gravatar in /.../st-manage-certificates-ui/node_modules/ng2-gravatar-directive/src/gravatar.d.ts' declared by the module 'ManageCertificatesModule in /.../st-manage-certificates-ui/src/app/manage-certificates/manage-certificates.module.ts'

"Module not found: Error: Can't resolve './$$_gendir/app/app.module.ngfactory' in '/Users/kenwilson/Documents/SemaTree/st-manage-certificates-ui/src'
 @ ./src/main.ts 4:0-74
 @ multi ./src/main.ts
"

**Comment by DenissKulakov** [comment]
Same issue!

**Comment by shotokai** [comment]
I had this as well.  Modifying the import in the module resolved it for me:
`import { Gravatar } from 'ng2-gravatar-directive/src/gravatar';`

**Comment by stkrwilson** [comment]
FANTASTIC!

worked for me too.

thank you

sincerely

**Comment by DenissKulakov** [comment]
thank you
